name: Deploy Resume

on:
  push:
    branches:
      - main # 当代码被推送到 main 分支时触发工作流程。

jobs:
  deploy:
    runs-on: ubuntu-latest # 在最新版本的 Ubuntu 上运行。

    steps:
      - name: Checkout # 检出代码。
        uses: actions/checkout@v2

      # 缓存依赖
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

        # 安装依赖
      - run: yarn

      # 打包构建
      - run: yarn build

      - name: Deploy # 部署站点。
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }} # 访问秘钥
          publish_branch: gh-pages # 推送分支
          publish_dir: docs # 发布目录为 docs


      # 如果在执行的时候报错，提示需要用户名跟邮箱，那么需要单独设置下邮箱跟用户名
      # - run: git config --global user.email "1440955662@qq.com"
      # - run: git config --global user.name "limubai"
